/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'BIRTHDAYS_EN_GB': {
        'alex': 'Alex\'s birthday is Summer 13',
        'elliott': 'Elliot\'s birthday is Fall 5',
        'harvey': 'Harvey\'s birthday is Winter 14',
        'sam': 'Sam\'s birthday is Summer 17',
        'sebastian': 'Sebastian\'s birthday is Winter 10',
        'shane': 'Shane\'s birthday is Spring 20',
        'abigail': 'Abigail\'s birthday is Fall 13',
        'emily': 'Emily\'s birthday is Spring 27',
        'haley': 'Haley\'s birthday is Spring 14',
        'leah': 'Leah\'s birthday is Winter 23',
        'maru': 'Maru\'s birthday is Summer 10',
        'penny': 'Penny\'s birthday is Fall 2',
        'caroline': 'Caroline\'s birthday is Winter 7',
        'clint': 'Clint\'s birthday is Winter 26',
        'demetrius': 'Demetrius\'s birthday is Summer 19',
        'evelyn': 'Evelyn\'s birthday is Winter 20',
        'george': 'George\'s birthday is Fall 24',
        'gus': 'Gus\'s birthday is Summer 8',
        'jas': 'Jas\'s birthday is Summer 4',
        'jodi': 'Jodi\'s birthday is Fall 11',
        'kent': 'Kent\'s birthday is Spring 4',
        'lewis': 'Lewis\'s birthday is Spring 7',
        'linus': 'Linus\'s birthday is Winter 3 ',
        'marnie': 'Marnie\'s birthday is Fall 18',
        'pam': 'Pam\'s birthday is Spring 18',
        'pierre': 'Pierre\'s birthday is Spring 26',
        'robin': 'Robin\'s birthday is Fall 21',
        'vincent': 'Vincent\'s birthday is Spring 10',
        'willy': 'Willy\'s birthday is Summer 24',
        'dwarf': 'Dwarf\'s birthday is Summer 22',
        'krobus': 'Krobus\'s birthday is Winter 1',
        'sandy': 'Sandy\'s birthday is Fall 15',
        'Wizard': 'Wizard\'s birthday is Winter 17',

        'alex\'s': 'Alex\'s birthday is Summer 13',
        'elliott\'s': 'Elliot\'s birthday is Fall 5',
        'harvey\'s': 'Harvey\'s birthday is Winter 14',
        'sam\'s': 'Sam\'s birthday is Summer 17',
        'sebastian\'s': 'Sebastian\'s birthday is Winter 10',
        'shane\'s': 'Shane\'s birthday is Spring 20',
        'abigail\'s': 'Abigail\'s birthday is Fall 13',
        'emily\'s': 'Emily\'s birthday is Spring 27',
        'haley\'s': 'Haley\'s birthday is Spring 14',
        'leah\'s': 'Leah\'s birthday is Winter 23',
        'maru\'s': 'Maru\'s birthday is Summer 10',
        'penny\'s': 'Penny\'s birthday is Fall 2',
        'caroline\'s': 'Caroline\'s birthday is Winter 7',
        'clint\'s': 'Clint\'s birthday is Winter 26',
        'demetrius\'s': 'Demetrius\'s birthday is Summer 19',
        'evelyn\'s': 'Evelyn\'s birthday is Winter 20',
        'george\'s': 'George\'s birthday is Fall 24',
        'gus\'s': 'Gus\'s birthday is Summer 8',
        'jas\'s': 'Jas\'s birthday is Summer 4',
        'jodi\'s': 'Jodi\'s birthday is Fall 11',
        'kent\'s': 'Kent\'s birthday is Spring 4',
        'lewis\'s': 'Lewis\'s birthday is Spring 7',
        'linus\'s': 'Linus\'s birthday is Winter 3 ',
        'marnie\'s': 'Marnie\'s birthday is Fall 18',
        'pam\'s': 'Pam\'s birthday is Spring 18',
        'pierre\'s': 'Pierre\'s birthday is Spring 26',
        'robin\'s': 'Robin\'s birthday is Fall 21',
        'vincent\'s': 'Vincent\'s birthday is Spring 10',
        'willy\'s': 'Willy\'s birthday is Summer 24',
        'dwarf\'s': 'Dwarf\'s birthday is Summer 22',
        'krobus\'s': 'Krobus\'s birthday is Winter 1',
        'sandy\'s': 'Sandy\'s birthday is Fall 15',
        'Wizard\'s': 'Wizard\'s birthday is Winter 17',

        'alexs': 'Alex\'s birthday is Summer 13',
        'elliotts': 'Elliot\'s birthday is Fall 5',
        'harveys': 'Harvey\'s birthday is Winter 14',
        'sams': 'Sam\'s birthday is Summer 17',
        'sebastians': 'Sebastian\'s birthday is Winter 10',
        'shanes': 'Shane\'s birthday is Spring 20',
        'abigails': 'Abigail\'s birthday is Fall 13',
        'emilys': 'Emily\'s birthday is Spring 27',
        'haleys': 'Haley\'s birthday is Spring 14',
        'leahs': 'Leah\'s birthday is Winter 23',
        'marus': 'Maru\'s birthday is Summer 10',
        'pennys': 'Penny\'s birthday is Fall 2',
        'carolines': 'Caroline\'s birthday is Winter 7',
        'clints': 'Clint\'s birthday is Winter 26',
        'demetriuss': 'Demetrius\'s birthday is Summer 19',
        'evelyns': 'Evelyn\'s birthday is Winter 20',
        'georges': 'George\'s birthday is Fall 24',
        'guss': 'Gus\'s birthday is Summer 8',
        'jass': 'Jas\'s birthday is Summer 4',
        'jodis': 'Jodi\'s birthday is Fall 11',
        'kents': 'Kent\'s birthday is Spring 4',
        'lewiss': 'Lewis\'s birthday is Spring 7',
        'linuss': 'Linus\'s birthday is Winter 3 ',
        'marnies': 'Marnie\'s birthday is Fall 18',
        'pams': 'Pam\'s birthday is Spring 18',
        'pierres': 'Pierre\'s birthday is Spring 26',
        'robins': 'Robin\'s birthday is Fall 21',
        'vincents': 'Vincent\'s birthday is Spring 10',
        'willys': 'Willy\'s birthday is Summer 24',
        'dwarfs': 'Dwarf\'s birthday is Summer 22',
        'krobuss': 'Krobus\'s birthday is Winter 1',
        'sandys': 'Sandy\'s birthday is Fall 15',
        'Wizards': 'Wizard\'s birthday is Winter 17'
    }
};
