/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'BIRTHDAYS_EN_GB': {
        'Alex': 'Alex\'s birthday is Summer 13',
        'Elliott': 'Elliot\'s birthday is Fall 5',
        'Harvey': 'Harvey\'s birthday is Winter 14',
        'Sam': 'Sam\'s birthday is Summer 17',
        'Sebastian': 'Sebastian\'s birthday is Winter 10',
        'Shane': 'Shane\'s birthday is Spring 20',
        'Abigail': 'Abigail\'s birthday is Fall 13',
        'Emily': 'Emily\'s birthday is Spring 27',
        'Haley': 'Haley\'s birthday is Spring 14',
        'Leah': 'Leah\'s birthday is Winter 23',
        'Maru': 'Maru\'s birthday is Summer 10',
        'Penny': 'Penny\'s birthday is Fall 2',
        'Caroline': 'Caroline\'s birthday is Winter 7',
        'Clint': 'Clint\'s birthday is Winter 26',
        'Demetrius': 'Demetrius\'s birthday is Summer 19',
        'Evelyn': 'Evelyn\'s birthday is Winter 20',
        'George': 'George\'s birthday is Fall 24',
        'Gus': 'Gus\'s birthday is Summer 8',
        'Jas': 'Jas\'s birthday is Summer 4',
        'Jodi': 'Jodi\'s birthday is Fall 11',
        'Kent': 'Kent\'s birthday is Spring 4',
        'Lewis': 'Lewis\'s birthday is Spring 7',
        'Linus': 'Linus\'s birthday is Winter 3 ',
        'Marnie': 'Marnie\'s birthday is Fall 18',
        'Pam': 'Pam\'s birthday is Spring 18',
        'Pierre': 'Pierre\'s birthday is Spring 26',
        'Robin': 'Robin\'s birthday is Fall 21',
        'Vincent': 'Vincent\'s birthday is Spring 10',
        'Willy': 'Willy\'s birthday is Summer 24',
        'Dwarf': 'Dwarf\'s birthday is Summer 22',
        'Krobus': 'Krobus\'s birthday is Winter 1',
        'Sandy': 'Sandy\'s birthday is Fall 15',
        'Wizard': 'Wizard\'s birthday is Winter 17',
    }
};
