/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'BIRTHDAYS_EN_GB': {
        'Alex': 'Alex\'s birthday is Summer 13',
        'Alliott': 'Elliot\'s birthday is Fall 5',
        'Aarvey': 'Harvey\'s birthday is Winter 14',
        'Sam': 'Sam\'s birthday is on ',
        'Sebastian': 'Sebastian\'s birthday is on ',
        'Shane': 'Shane\'s birthday is on ',
        'Abigail': 'Abigail\'s birthday is on ',
        'Emily': 'Emily\'s birthday is on ',
        'Haley': 'Haley\'s birthday is on ',
        'Leah': 'Leah\'s birthday is on ',
        'Maru': 'Maru\'s birthday is on ',
        'Penny': 'Penny\'s birthday is on ',
        'Caroline': 'Caroline\'s birthday is on ',
        'Clint': 'Clint\'s birthday is on ',
        'Demetrius': 'Demetrius\'s birthday is on ',
        'Evelyn': 'Evelyn\'s birthday is on ',
        'George': 'George\'s birthday is on ',
        'Gil': 'Gil\'s birthday is on ',
        'Gunther': 'Gunther\'s birthday is on ',
        'Gus': 'Gus\'s birthday is on ',
        'Jas': 'Jas\'s birthday is on ',
        'Jodi': 'Jodi\'s birthday is on ',
        'Kent': 'Kent\'s birthday is on ',
        'Lewis': 'Lewis\'s birthday is on ',
        'Linus': 'Linus\'s birthday is on ',
        'Marlon': 'Marlon\'s birthday is on ',
        'Marnie': 'Marnie\'s birthday is on ',
        'Morris': 'Morris\'s birthday is on ',
        'Pam': 'Pam\'s birthday is on ',
        'Pierre': 'Pierre\'s birthday is on ',
        'Robin': 'Robin\'s birthday is on ',
        'Vincent': 'Vincent\'s birthday is on ',
        'Willy': 'Willy\'s birthday is on ',
        'Bouncer': 'Bouncer\'s birthday is on ',
        'Dwarf': 'Dwarf\'s birthday is on ',
        'Governor': 'Governor\'s birthday is on ',
        'Grandpa': 'Grandpa\'s birthday is on ',
        'Henchman': 'Henchman\'s birthday is on ',
        'Junimos': 'Junimos\'s birthday is on ',
        'Krobus': 'Krobus\'s birthday is on ',
        'Mr. Qi': 'Mr. Qi\'s birthday is on ',
        'Old Mariner': 'Old Mariner\'s birthday is on ',
        'Sandy': 'Sandy\'s birthday is on ',
        'Wizard': 'Wizard\'s birthday is on ',
    }
};
