/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'HOMES_EN_GB': {
        'alex': 'Alex lives in the house southeast of Pierre\'s General Store, at 1 River Road',
        'elliott': 'Elliot lives on the beach south of Pelican Town',
        'harvey': 'Harvey lives in the medical clinic in Pelican Town.',
        'sam': 'Sam lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'sebastian': 'Sebastian lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'shane': 'Shane lives at Marnie\'s Ranch in the northeast area of Cindersap Forest, near the southwest entrance to Pelican Town.',
        'abigail': 'Abigail lives at Pierre\'s General Store in Pelican Town',
        'emily': 'Emily lives south of the town square, right next to Jodi\'s, at 2 Willow Lane.',
        'haley': 'Haley lives south of the town square, right next to Jodi\'s, at 2 Willow Lane.',
        'leah': 'Leah lives in a small cottage outside Pelican Town, in Cindersnap forest.',
        'maru': 'Maru lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'penny': 'Penny lives in a trailer just east of the center of town, west of the river.',
        'caroline': 'Caroline lives at Pierre\'s General Store in Pelican Town',
        'clint': 'Clint lives at the blacksmith.',
        'demetrius': 'Demetrius lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'evelyn': 'Evelyn lives in the house southeast of Pierre\'s General Store, at 1 River Road',
        'george': 'George lives in the house southeast of Pierre\'s General Store, at 1 River Road',
        'gus': 'Gus lives and works at The Stardrop Saloon in Pelican Town',
        'jas': 'Jas lives at Marnie\'s Ranch in the northeast area of Cindersap Forest, near the southwest entrance to Pelican Town.',
        'jodi': 'Jodi lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'kent': 'Kent lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'lewis': 'Lewis lives at Mayor\'s Manor, east of the graveyard, next to the bridge leading to the museum and Blacksmith.',
        'linus': 'Linus lives in a small tent north of Pelican Town, near The Mines.',
        'marlon': 'Marlon lives at lives in the North East of Pelican Town, in the Adventurer\'s Guild',
        'marnie': 'Marnie lives at her Ranch in the northeast area of Cindersap Forest, near the southwest entrance to Pelican Town.',
        'morris': 'Morris works at JojaMart in Pelican Town.',
        'pam': 'Pam lives in the trailer just west of the river in Pelican Town',
        'pierre': 'Pierre lives at his General Store in Pelican Town',
        'pobin': 'Robin lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'vincent': 'Vincent lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'willy': 'Willy lives on the beach at his fishing shop.',
        'bouncer': 'Bouncer works at the Casino, located at the back of Oasis',
        'dwarf': 'The Dwarf lives in the mines in the north area of the Mountains ',
        'governor': 'The Governor does not live in pelican town',
        'grandpa': 'Grandpa lives in heaven.',
        'henchman': 'The Henchman lives at the witches swamp.',
        'junimos': 'Junimos live at the community center.',
        'krobus': 'Krobus lives in the sewers',
        'mr. Qi': 'Mr. Qi works at the Casino.',
        'sandy': 'Sandy works at the Casino',
        'wizard': 'Wizard lives in the Wizard\'s Tower to the far west of Cindersap Forest.'
    }
};
