/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'HOMES_EN_GB': {
        'Alex': 'Alex lives in the house southeast of Pierre\'s General Store, at 1 River Road',
        'Elliott': 'Elliot lives on the beach south of Pelican Town',
        'Harvey': 'Harvey lives in the medical clinic in Pelican Town.',
        'Sam': 'Sam lives at',
        'Sebastian': 'Sebastian lives at',
        'Shane': 'Shane lives at',
        'Abigail': 'Abigail lives at',
        'Emily': 'Emily lives at',
        'Haley': 'Haley lives at',
        'Leah': 'Leah lives at',
        'Maru': 'Maru lives at',
        'Penny': 'Penny lives at',
        'Caroline': 'Caroline lives at',
        'Clint': 'Clint lives at',
        'Demetrius': 'Demetrius lives at',
        'Evelyn': 'Evelyn lives at',
        'George': 'George lives at',
        'Gil': 'Gil lives at',
        'Gunther': 'Gunther lives at',
        'Gus': 'Gus lives at',
        'Jas': 'Jas lives at',
        'Jodi': 'Jodi lives at',
        'Kent': 'Kent lives at',
        'Lewis': 'Lewis lives at',
        'Linus': 'Linus lives at',
        'Marlon': 'Marlon lives at',
        'Marnie': 'Marnie lives at',
        'Morris': 'Morris lives at',
        'Pam': 'Pam lives at',
        'Pierre': 'Pierre lives at',
        'Robin': 'Robin lives at',
        'Vincent': 'Vincent lives at',
        'Willy': 'Willy lives at',
        'Bouncer': 'Bouncer lives at',
        'Dwarf': 'Dwarf lives at',
        'Governor': 'Governor lives at',
        'Grandpa': 'Grandpa lives at',
        'Henchman': 'Henchman lives at',
        'Junimos': 'Junimos lives at',
        'Krobus': 'Krobus lives at',
        'Mr. Qi': 'Mr. Qi lives at',
        'Old Mariner': 'Old Mariner lives at',
        'Sandy': 'Sandy lives at',
        'Wizard': 'Wizard lives at',
    }
};
