/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'HOMES_EN_GB': {
        'Alex': 'Alex lives in the house southeast of Pierre\'s General Store, at 1 River Road',
        'Elliott': 'Elliot lives on the beach south of Pelican Town',
        'Harvey': 'Harvey lives in the medical clinic in Pelican Town.',
        'Sam': 'Sam lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'Sebastian': 'Sebastian lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'Shane': 'Shane lives at Marnie\'s Ranch in the northeast area of Cindersap Forest, near the southwest entrance to Pelican Town.',
        'Abigail': 'Abigail lives at Pierre\'s General Store in Pelican Town',
        'Emily': 'Emily lives south of the town square, right next to Jodi\'s, at 2 Willow Lane.',
        'Haley': 'Haley lives south of the town square, right next to Jodi\'s, at 2 Willow Lane.',
        'Leah': 'Leah lives in a small cottage outside Pelican Town, in Cindersnap forest.',
        'Maru': 'Maru lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'Penny': 'Penny lives in a trailer just east of the center of town, west of the river.',
        'Caroline': 'Caroline lives at Pierre\'s General Store in Pelican Town',
        'Clint': 'Clint lives at the blacksmith.',
        'Demetrius': 'Demetrius lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'Evelyn': 'Evelyn lives in the house southeast of Pierre\'s General Store, at 1 River Road',
        'George': 'George lives in the house southeast of Pierre\'s General Store, at 1 River Road',
        'Gus': 'Gus lives and works at The Stardrop Saloon in Pelican Town',
        'Jas': 'Jas lives at Marnie\'s Ranch in the northeast area of Cindersap Forest, near the southwest entrance to Pelican Town.',
        'Jodi': 'Jodi lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'Kent': 'Kent lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'Lewis': 'Lewis lives at Mayor\'s Manor, east of the graveyard, next to the bridge leading to the museum and Blacksmith.',
        'Linus': 'Linus lives in a small tent north of Pelican Town, near The Mines.',
        'Marlon': 'Marlon lives at lives in the North East of Pelican Town, in the Adventurer\'s Guild',
        'Marnie': 'Marnie lives at her Ranch in the northeast area of Cindersap Forest, near the southwest entrance to Pelican Town.',
        'Morris': 'Morris works at JojaMart in Pelican Town.',
        'Pam': 'Pam lives in the trailer just west of the river in Pelican Town',
        'Pierre': 'Pierre lives at his General Store in Pelican Town',
        'Robin': 'Robin lives in The Mountains north of Pelican Town, at 24 Mountain Road',
        'Vincent': 'Vincent lives in the southern part of town, just north of the river, at 1 Willow Lane.',
        'Willy': 'Willy lives on the beach at his fishing shop.',
        'Bouncer': 'Bouncer works at the Casino, located at the back of Oasis',
        'Dwarf': 'The Dwarf lives in the mines in the north area of the Mountains ',
        'Governor': 'The Governor does not live in pelican town',
        'Grandpa': 'Grandpa lives in heaven.',
        'Henchman': 'The Henchman lives at the witches swamp.',
        'Junimos': 'Junimos live at the community center.',
        'Krobus': 'Krobus lives in the sewers',
        'Mr. Qi': 'Mr. Qi works at the Casino.',
        'Sandy': 'Sandy works at the Casino,',
        'Wizard': 'Wizard lives in the Wizard\'s Tower to the far west of Cindersap Forest.',
    }
};
